package com.drones.vision.adapter.persistence.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * JPA row for {@code db_audit_log} — the database-level change audit ({@code
 * V21__db_audit_log.sql}). Every row here is written by that migration's {@code
 * audit_row_change()} trigger function, never by application code (this module has no matching
 * {@code save}/{@code persist} caller and never will — see {@link
 * com.drones.vision.adapter.persistence.repository.JpaDbAuditLogRepository}'s own javadoc for
 * why this entity is read-only). This is <strong>not</strong> {@link AuditEntryEntity}: that one
 * mirrors a domain aggregate ({@code AuditEntry}) an application service explicitly records;
 * this one mirrors an arbitrary row from any of seventeen different audited tables, so its
 * {@code oldRow}/{@code newRow} carry no fixed shape — see this class's own package's
 * MODULE.md ("Database change audit") for the full distinction between the two tables.
 *
 * <p>{@code id} is a synthetic {@code BIGINT GENERATED ALWAYS AS IDENTITY} column, not a UUID —
 * unlike every other synthetic id in this module (a random {@code UUID} invented in Java, e.g.
 * {@code TelemetrySampleEntity#id}), this id is generated by Postgres itself inside the trigger
 * that writes the row, so a database-native identity column is the natural fit; nothing outside
 * this table ever needs to reference it.
 *
 * <p>{@code rowId} is always text even though every primary key in this schema is in fact a
 * {@code UUID} (or, for a handful of composite-key join tables, several) — {@code
 * audit_row_change()} resolves it generically from the catalog and cannot assume a single
 * uniform key shape across seventeen different audited tables.
 *
 * <p>{@code oldRow}/{@code newRow}/{@code changedColumns} are jsonb, mapped generically as
 * {@code Map<String, Object>}/{@code List<String>} rather than any fixed record type — same
 * mechanism (Hibernate's Jackson-3-backed {@code FormatMapper}) as every other jsonb column in
 * this module, but with no fixed Java shape on the far side, since the row image can be any of
 * this schema's audited tables. {@code oldRow} is {@code null} for an {@code INSERT}, {@code
 * newRow} is {@code null} for a {@code DELETE}, and {@code changedColumns} is only ever
 * populated for an {@code UPDATE} — the trigger leaves it {@code null} for the other two
 * operations rather than fabricating an empty list.
 */
@Entity
@Table(name = "db_audit_log")
public class DbAuditLogEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    private Long id;

    @Column(name = "occurred_at", nullable = false)
    private Instant occurredAt;

    @Column(name = "table_name", nullable = false)
    private String tableName;

    @Column(name = "row_id", nullable = false)
    private String rowId;

    @Enumerated(EnumType.STRING)
    @Column(name = "operation", nullable = false, length = 6)
    private DbAuditOperation operation;

    @Column(name = "db_user", nullable = false)
    private String dbUser;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "old_row", columnDefinition = "jsonb")
    private Map<String, Object> oldRow;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "new_row", columnDefinition = "jsonb")
    private Map<String, Object> newRow;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "changed_columns", columnDefinition = "jsonb")
    private List<String> changedColumns;

    /** JPA only. */
    protected DbAuditLogEntity() {
    }

    public DbAuditLogEntity(Long id, Instant occurredAt, String tableName, String rowId, DbAuditOperation operation,
                             String dbUser, Map<String, Object> oldRow, Map<String, Object> newRow,
                             List<String> changedColumns) {
        this.id = id;
        this.occurredAt = occurredAt;
        this.tableName = tableName;
        this.rowId = rowId;
        this.operation = operation;
        this.dbUser = dbUser;
        this.oldRow = oldRow;
        this.newRow = newRow;
        this.changedColumns = changedColumns;
    }

    public Long id() {
        return id;
    }

    public Instant occurredAt() {
        return occurredAt;
    }

    public String tableName() {
        return tableName;
    }

    public String rowId() {
        return rowId;
    }

    public DbAuditOperation operation() {
        return operation;
    }

    public String dbUser() {
        return dbUser;
    }

    public Map<String, Object> oldRow() {
        return oldRow;
    }

    public Map<String, Object> newRow() {
        return newRow;
    }

    public List<String> changedColumns() {
        return changedColumns;
    }
}
