package com.drones.vision.map.application.track;

import com.drones.vision.kernel.BearingDistance;
import com.drones.vision.kernel.FixedCameraPose;
import com.drones.vision.kernel.GeoPosition;
import com.drones.vision.kernel.GeoProjection;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Locale;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises {@link CameraCalibrationSolver} against synthetic landmarks generated by forward
 * projection through a known pose, so a round-trip solve can be checked against a known-true
 * answer (docs/plans/done/FIXED-CAMERA-GEO-PLAN.md D5) instead of only against hand-picked
 * refusal fixtures.
 */
class CameraCalibrationSolverTest {

    private static final GeoPosition CAMERA_POSITION = new GeoPosition(50.45, 30.52, null);
    private static final double AGL_METERS = 50.0;
    private static final double YAW_DEGREES = 30.0;
    private static final double PITCH_DEGREES = 20.0;
    private static final double HFOV_DEGREES = 60.0;
    private static final int IMAGE_WIDTH_PIXELS = 1920;
    private static final int IMAGE_HEIGHT_PIXELS = 1080;

    /** Forward-projects a normalized pixel {@code (u,v)} through the known synthetic pose, exactly
     * the inverse of what {@link CameraCalibrationSolver} fits, so a landmark is geometrically
     * consistent with the pose the round-trip test recovers. */
    private static CalibrationLandmark landmark(double u, double v) {
        double halfHfovTangent = Math.tan(Math.toRadians(HFOV_DEGREES) / 2.0);
        double aspectRatio = (double) IMAGE_HEIGHT_PIXELS / (double) IMAGE_WIDTH_PIXELS;
        double azimuthOffsetDegrees = Math.toDegrees(Math.atan((2.0 * u - 1.0) * halfHfovTangent));
        double depressionOffsetDegrees = Math.toDegrees(Math.atan((2.0 * v - 1.0) * halfHfovTangent * aspectRatio));

        double azimuthDegrees = YAW_DEGREES + azimuthOffsetDegrees;
        double depressionDegrees = PITCH_DEGREES + depressionOffsetDegrees;

        GeoPosition mapPosition = GeoProjection.project(CAMERA_POSITION, azimuthDegrees, AGL_METERS, depressionDegrees);
        return new CalibrationLandmark(u, v, mapPosition);
    }

    private static CalibrationRequest request(List<CalibrationLandmark> landmarks) {
        return new CalibrationRequest(CAMERA_POSITION, AGL_METERS, IMAGE_WIDTH_PIXELS, IMAGE_HEIGHT_PIXELS, landmarks);
    }

    // --- Round trip: 3+ consistent landmarks solve GOOD with sub-pixel residual -----------------

    @Test
    void solvesThreePointRoundTripUnderOnePixelRms() {
        List<CalibrationLandmark> landmarks =
                List.of(landmark(0.25, 0.55), landmark(0.5, 0.65), landmark(0.8, 0.45));

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 5.0);

        assertTrue(result.solved(), () -> "expected solved, got refusal: " + result.reason());
        assertEquals(CalibrationQuality.GOOD, result.quality());
        assertTrue(result.rmsErrorPixels() < 1.0, "rmsErrorPixels=" + result.rmsErrorPixels());

        FixedCameraPose pose = result.pose();
        assertEquals(YAW_DEGREES, pose.yawDegrees(), 0.5);
        assertEquals(PITCH_DEGREES, pose.pitchDegrees(), 0.5);
        assertEquals(HFOV_DEGREES, pose.hfovDegrees(), 0.5);
        assertEquals(CAMERA_POSITION, pose.position());
        assertEquals(AGL_METERS, pose.aglMeters(), 1e-9);
    }

    // --- Exactly 2 landmarks: consistent ones solve UNDETERMINED, inconsistent ones still refuse --

    @Test
    void exactlyTwoConsistentLandmarksSolveButReportUndetermined() {
        List<CalibrationLandmark> landmarks = List.of(landmark(0.2, 0.5), landmark(0.8, 0.6));

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 5.0);

        assertTrue(result.solved(), () -> "expected solved, got refusal: " + result.reason());
        assertEquals(CalibrationQuality.UNDETERMINED, result.quality());
        assertNotNull(result.rmsErrorPixels());
        assertTrue(result.rmsErrorPixels() < 1.0, "rmsErrorPixels=" + result.rmsErrorPixels());
    }

    /**
     * The defect a live run of {@code POST /api/assets/{id}/camera-pose/calibration} exposed: D5
     * exempted {@code N == 2} from the residual ceiling, calling the fit "exact." Two landmarks
     * give four measurements against three unknowns, so the residual is real — and two mutually
     * inconsistent clicks were coming back {@code solved:true} with a 177-pixel residual and a pose
     * wrong by 10° of yaw, offered to the operator as savable.
     */
    @Test
    void twoMutuallyInconsistentLandmarksRefuseInsteadOfReturningAConfidentWrongPose() {
        // Second landmark's map position belongs to a different pixel entirely -- no single
        // yaw/pitch/hfov explains the pair, and the leftover residual says so.
        CalibrationLandmark elsewhere = landmark(0.8, 0.45);
        List<CalibrationLandmark> landmarks =
                List.of(landmark(0.2, 0.5), new CalibrationLandmark(0.35, 0.75, elsewhere.mapPosition()));

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 25.0);

        assertFalse(result.solved(), () -> "expected refusal, got a pose with rms " + result.rmsErrorPixels());
        assertTrue(result.reason().startsWith("residual "), () -> "reason=" + result.reason());
        assertNull(result.quality());
    }

    // --- Degenerate geometry: landmarks radially collinear refuse on bearing spread -------------

    @Test
    void collinearLandmarksRefuseWithBearingSpreadReason() {
        // u == 0.5 for every landmark means zero azimuth offset from yaw for each -- they differ
        // only in depression (v), so as seen from the camera they sit on (almost) the same bearing.
        List<CalibrationLandmark> landmarks = List.of(landmark(0.5, 0.4), landmark(0.5, 0.6));

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 5.0);

        assertFalse(result.solved());
        assertTrue(result.reason().contains("span only"), () -> "reason=" + result.reason());
        assertTrue(result.reason().endsWith("° of bearing"), () -> "reason=" + result.reason());
        assertNull(result.rmsErrorPixels());
    }

    // --- Degenerate geometry: a too-close landmark refuses on distance ---------------------------

    @Test
    void tooCloseLandmarkRefusesWithDistanceReason() {
        // A landmark ~2cm from the camera -- well under the 3m minimum -- placed first so its
        // 1-based index in the reason string is deterministic.
        GeoPosition tooClose = GeoProjection.project(CAMERA_POSITION, 0.0, 1.0, 89.0);
        BearingDistance actualDistance = GeoProjection.bearingDistance(CAMERA_POSITION, tooClose);
        List<CalibrationLandmark> landmarks =
                List.of(new CalibrationLandmark(0.5, 0.5, tooClose), landmark(0.8, 0.45));

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 5.0);

        assertFalse(result.solved());
        String expectedReason = String.format(Locale.ROOT, "landmark 1 is %sm from the camera",
                String.format(Locale.ROOT, "%.1f", actualDistance.distanceMeters()));
        assertEquals(expectedReason, result.reason());
        assertNull(result.rmsErrorPixels());
    }

    // --- N>=3 fit whose residual exceeds the ceiling refuses -------------------------------------

    @Test
    void residualBeyondCeilingRefusesWithResidualExceedsReason() {
        // Three geometrically consistent landmarks plus a fourth whose pixel coordinate is shifted
        // far from where its (unchanged) map position actually is -- no single hfov/yaw/pitch can
        // fit all four, so the residual stays large regardless of the search.
        CalibrationLandmark trueLandmark = landmark(0.65, 0.5);
        CalibrationLandmark corrupted = new CalibrationLandmark(0.5, trueLandmark.v(), trueLandmark.mapPosition());
        List<CalibrationLandmark> landmarks =
                List.of(landmark(0.25, 0.55), landmark(0.5, 0.65), landmark(0.8, 0.45), corrupted);

        CalibrationResult result = CameraCalibrationSolver.solve(request(landmarks), 5.0);

        assertFalse(result.solved());
        assertTrue(result.reason().contains("exceeds"), () -> "reason=" + result.reason());
        assertTrue(result.reason().startsWith("residual "), () -> "reason=" + result.reason());
        assertTrue(result.rmsErrorPixels() != null && result.rmsErrorPixels() > 5.0);
    }
}
