"""Harness self-tests for the H0 eval harness (VISUAL-GEO-V2-PLAN.md §5 H0) -- pure math and
plumbing only, zero network/model dependencies (no torch/kornia/cv2 forward pass, no live tile
fetch, no built region on disk). Run with:

    cd cv-service && .venv/bin/python -m pytest spikes -q

The bake-off/false-convergence-gate scripts themselves (`run_bakeoff.py`,
`false_convergence_gate.py`, `build_regions.py`'s actual fetch+build) are exercised by hand against
live Esri tiles + real matcher models, not here -- see `spikes/geo/results/report.md` for those
measured runs. This file locks in the pure helpers those scripts share, so a refactor can't
silently break the distance/config-key/manifest-roundtrip math the measured numbers depend on.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from spikes.geo import metrics
from spikes.geo import report as report_mod
from spikes.geo.build_regions import REGION_SPECS
from spikes.geo.manifest import QueryFrame, load_manifest, write_manifest
from spikes.geo.run_bakeoff import DATASETS, REFUSED_RECTIFIED_NO_TELEMETRY, _config_key, haversine_m


# --------------------------------------------------------------------------- haversine_m


def test_haversine_same_point_is_zero():
    assert haversine_m(50.45, 30.52, 50.45, 30.52) == pytest.approx(0.0, abs=1e-6)


def test_haversine_known_distance_kyiv_pair():
    # Maidan Nezalezhnosti monument -> the branch's own known-wrong Pexels cell, both real
    # coordinates already used in this wave's measured report (00-existing-state.md §2):
    # 50.4502431N,30.5240622E vs the "17/76646/44193" tile center, ~775m per the branch's own
    # finding -- loose bounds since our tile-center math differs slightly from the branch's.
    truth = (50.4502431, 30.5240622)
    wrong_cell_approx = (50.4572, 30.5195)  # north-west of truth, same ballpark as the real cell
    d = haversine_m(*truth, *wrong_cell_approx)
    assert 500.0 < d < 1200.0


def test_haversine_is_symmetric():
    a, b = (50.40, 30.60), (50.45, 30.65)
    assert haversine_m(*a, *b) == pytest.approx(haversine_m(*b, *a), rel=1e-9)


# --------------------------------------------------------------------------- run_bakeoff plumbing


def test_config_key_is_stable_and_distinguishes_every_axis():
    base = _config_key("pexels", "xfeat", True, 10)
    assert base == _config_key("pexels", "xfeat", True, 10)  # deterministic
    assert base != _config_key("pexels", "xfeat", False, 10)  # rectified axis
    assert base != _config_key("pexels", "loftr", True, 10)  # matcher axis
    assert base != _config_key("pexels", "xfeat", True, 5)  # k axis
    assert base != _config_key("sitl-nadir", "xfeat", True, 10)  # dataset axis


def test_datasets_registry_points_at_files_that_exist_or_are_runtime_artefacts():
    # pexels' manifest is COMMITTED fixture data -- must exist. The sitl-* manifests are
    # generated by sitl_render.py into a gitignored results/ subdir -- only assert the dataset
    # keys/shape are sane, not that those files exist (a clean checkout won't have them yet).
    assert set(DATASETS) == {"pexels", "sitl-nadir", "sitl-oblique45"}
    assert DATASETS["pexels"]["manifest"].exists(), "the committed Pexels fixture manifest must exist"
    for spec in DATASETS.values():
        assert spec["region_id"] == "kyiv-maidan"


def test_rectified_pexels_is_refused_not_faked():
    # run_config's own early-return string (see module docstring) -- pinned here so nobody
    # "fixes" this into silently fabricating a heading/altitude prior for a clip that has none.
    assert "no heading/altitude telemetry" in REFUSED_RECTIFIED_NO_TELEMETRY


# --------------------------------------------------------------------------- build_regions specs


def test_region_specs_tile_counts_match_the_branchs_own_build_scripts():
    pozniaky = REGION_SPECS["pozniaky"]
    maidan = REGION_SPECS["maidan"]
    assert len(pozniaky["x_range"]) * len(pozniaky["y_range"]) == 252
    assert len(maidan["x_range"]) * len(maidan["y_range"]) == 49
    assert pozniaky["region_id"] == "kyiv-pozniaky"
    assert maidan["region_id"] == "kyiv-maidan"


# --------------------------------------------------------------------------- rerank pure math


def test_reprojection_rms_zero_for_a_perfect_identity_fit():
    from spikes.geo.rerank import _reprojection_rms

    pts = np.array([[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 10.0], [5.0, 5.0]])
    H = np.eye(3)
    mask = np.ones((pts.shape[0], 1), dtype=np.uint8)
    rms = _reprojection_rms(pts, pts, H, mask)
    assert rms == pytest.approx(0.0, abs=1e-9)


def test_reprojection_rms_ignores_outlier_mask_entries():
    from spikes.geo.rerank import _reprojection_rms

    kp_query = np.array([[0.0, 0.0], [10.0, 0.0], [999.0, 999.0]])  # last is a wild outlier
    kp_tile = np.array([[0.0, 0.0], [10.0, 0.0], [-500.0, 500.0]])
    H = np.eye(3)
    mask = np.array([[1], [1], [0]], dtype=np.uint8)  # outlier excluded
    rms = _reprojection_rms(kp_query, kp_tile, H, mask)
    assert rms == pytest.approx(0.0, abs=1e-9)


def test_reprojection_rms_none_when_no_inliers():
    from spikes.geo.rerank import _reprojection_rms

    pts = np.array([[0.0, 0.0], [10.0, 0.0]])
    H = np.eye(3)
    mask = np.zeros((2, 1), dtype=np.uint8)
    assert _reprojection_rms(pts, pts, H, mask) is None


# --------------------------------------------------------------------------- manifest roundtrip


def test_manifest_roundtrip_preserves_altitude_meters(tmp_path: Path):
    frames = [
        QueryFrame(query_id="a", image_path=tmp_path / "a.jpg", lat=50.1, lon=30.1, heading=90.0, timestamp_ms=0, altitude_meters=75.5),
        QueryFrame(query_id="b", image_path=tmp_path / "b.jpg", lat=50.2, lon=30.2),  # no telemetry at all -- the Pexels shape
    ]
    manifest_path = tmp_path / "manifest.jsonl"
    write_manifest(manifest_path, frames)
    loaded = load_manifest(manifest_path)
    assert len(loaded) == 2
    assert loaded[0].altitude_meters == pytest.approx(75.5)
    assert loaded[0].heading == pytest.approx(90.0)
    assert loaded[1].altitude_meters is None
    assert loaded[1].heading is None


def test_pexels_fixture_manifest_is_a_single_grounded_location():
    # The committed fixture (H0's own harvest): 12 frames of a documented near-static hover, one
    # ground-truth point (VISUAL-GEO-V2-PLAN.md / 00-existing-state.md §2), no telemetry.
    manifest_path = Path(__file__).resolve().parents[1] / "fixtures" / "maidan-video-frames" / "manifest.jsonl"
    frames = load_manifest(manifest_path)
    assert len(frames) == 12
    lats = {f.lat for f in frames}
    lons = {f.lon for f in frames}
    assert lats == {50.4502431}
    assert lons == {30.5240622}
    assert all(f.heading is None and f.altitude_meters is None for f in frames)


# --------------------------------------------------------------------------- metrics.py / report.py (pre-existing, exercised here)


def _outcome(true_lat, true_lon, top1_lat, top1_lon, similarity, distance_m):
    return metrics.QueryOutcome(
        query_id="q", true_lat=true_lat, true_lon=true_lon, timestamp_ms=None,
        top1_lat=top1_lat, top1_lon=top1_lon, top1_similarity=similarity, margin=0.1,
        top1_distance_m=distance_m, best5_within_100m=distance_m <= 100.0,
        encode_ms=10.0, search_ms=1.0, n_candidates=5,
    )


def test_compute_config_metrics_recall_and_false_fix_rate():
    outcomes = [
        _outcome(50.0, 30.0, 50.0, 30.0, 0.9, 5.0),  # good, high sim
        _outcome(50.0, 30.0, 51.0, 31.0, 0.85, 500.0),  # false fix if accepted at a low threshold
        _outcome(50.0, 30.0, 50.0001, 30.0001, 0.6, 15.0),  # good, lower sim
    ]
    config = metrics.compute_config_metrics(
        config_name="t", encoder_name="e", zoom=17, augmented=False, with_prior=False, outcomes=outcomes
    )
    assert config.n_queries == 3
    assert config.recall_at_1_100m == pytest.approx(2 / 3)
    assert 0.0 <= config.false_fix_rate <= 1.0


def test_report_render_smoke():
    outcomes = [_outcome(50.0, 30.0, 50.0, 30.0, 0.9, 5.0)]
    config = metrics.compute_config_metrics(
        config_name="smoke", encoder_name="eigenplaces_r18_512", zoom=17, augmented=False,
        with_prior=False, outcomes=outcomes,
    )
    verdict = report_mod.compute_encoder_verdict("eigenplaces_r18_512", [config])
    text = report_mod.render_markdown(
        run_id="test-run", smoke_test=True, configs=[config],
        encoder_verdicts=[verdict], verdict=verdict, notes=["a note"],
    )
    assert "smoke" in text
    assert isinstance(text, str) and len(text) > 0
